name = "mehrabicraftpack"
author = "Kian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c7e8e2999f52aa25a74597aa2f08c5aed04102aaa5aed4a0ef0971b8a247ae0"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
