name = "mehrabicraftpack"
author = "Kian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d840149367a5d8ce7a621ed8f6aac65ab3b7d5e5cbef8c16d49a9d03a052ae5d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
